### PR TITLE
Updated file-list, with diffstat info

### PR DESCRIPTION
**Pull request by kelan**
I mentioned a while ago on the mailing list that I was working on this.  It got pushed to the back-burner for a while, but I think it's ready to go now.  Let me know what you think.

Here is a preview of what it looks like:
http://emberapp.com/kelan/images/new-gitx-filelist-with-diffstat-info

### CODE REVIEW

**Comment by brotherbard** [comment]
This looks really good. Thanks.

Unfortunately the contextual menu for files is broken.

As a start add the following at line 385 in history.js:
    fileElem.setAttribute("representedFile", fileInfo.filename);

This works for modified, added and deleted files but is still broken for file renames because `fileInfo.filename` is the full display name and not just the new file name. So you will need to add some way to get the renamed file name to put in the `representedFile` attribute.

This attribute is used in PBWebHistoryController webView:contextMenuItemsForElement:defaultMenuItems: to determine which menu to show and, obviously, the file to act on.

**Comment by kelan** [comment]
Ah, I didn't realize there was a contextual menu on the files.  I'll work on fixing that.

Thanks for the quick feedback!

**Comment by kelan** [comment]
This fixes that contextual menu and also a few bugs that I had in there (for example: commits that added files with spaces in the name didn't show the right icon).  I think I've now tested all cases of modify/add/remove/rename, including filenames with spaces.

On another note, do you have any comments/thoughts about the visual design of the new filelist?  I think it's not bad, but it doesn't really blow me away either...  I wanted to get these functional changes out there, and figured I could continue to iterate on the design.  But, I'd definitely be curious to hear any feedback you have about it.  Thanks!

**Comment by kelan** [comment]
Just noticed this is still showing up in my global list of open PRs. I think it's time has past, so time to say goodbye to it.

**Pull request closed without merging**
