### PR TITLE
Show history in date order

### PR DESCRIPTION
**Pull request by onnlucky**
Added an option to show history in date order, instead of topological order.

I always found GitX very strange in this regard ... by date is just that much more information about what is new and what has changed, which is what history is all about, no?

### CODE REVIEW

**Comment by tmiller** [comment]
+1

**Comment by felixyz** [comment]
This is already possible. Just click the date column header.

**Comment by onnlucky** [comment]
Hitting the date column is not the same. That will remove the graphical view and make everything flatten out. That is hardly of any use.

Letting git sort by date, as per patch, lets you view all the history and branch lines, and you see how it all connects, but you see the latest commits on top, even if they are in different and unrelated branches, and you can see how they do relate by tracing the lines back.

(I guess a picture is worth a thousand words here, but I hope you get the idea.)

**Comment by felixyz** [comment]
Understood. I thought I might be missing something. Would be useful indeed.

**Comment by Uncommon** [comment]
What happens if you've used rebase to change the order of some commits?

**Comment by onnlucky** [comment]
@Uncommon makes no difference, they will be shown under their new date, when gitx refreshes its view or you hit refresh or ...

**Pull request closed without merging**
