### PR TITLE
Open in Textmate

### PR DESCRIPTION
**Pull request by benlangfeld**
Just a simple addition. This is really useful for me, even if it is a horrible solution....

### CODE REVIEW

**Comment by koraktor** [comment]
To be honest, I don't like "links" to other non-standard applications. I'm not a Textmate user, so this toolbar item is completely useless for me.

This should be optional, if anything.

**Comment by benlangfeld** [comment]
Disabled in toolbar by default. I think this is worth having as an option even if you don't use it. Leaving out useful features because only 30% (or whichever other arbitrary number you fancy) of users want it would be unfortunate.

**Comment by ghost** [comment]
why not let users set their preferred editor in the preferences.  I use TextWrangler for some stuff as it can handle large texts better than TextMate.  The idea is good.

**Comment by benlangfeld** [comment]
I like the idea, but I don't have time to look at it right now.

**Comment by boxed** [comment]
In most views there's a right-click/ctrl-click option to open the file. This works just like double-clicking in finder, which seems reasonable. If you're a TextMate user you probably have your mac set up so it opens in textmate. If this command just had a toolbar entry and a hotkey it should be sufficient I think.

**Comment by benlangfeld** [comment]
Boxed: This commit as it stands opens the entire directory in TextMate, rather than an individual file.

**Comment by boxed** [comment]
Ah. Gotcha.

**Pull request closed without merging**
